export const arrayItems =[{
    name : 'Q&A',
    id : 'q&a',
    description : "Answer question based on knowledge",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'Grammer corrections',
    id : 'grammerCorrections',
    description : "Correct sentence into standard english",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'Summarize for a second grader',
    id : 'summary',
    description : "Translate difficult text into simpler concepts",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'English Into Other language',
    id : 'translate',
    description : "Translate english text to other language",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'Movie to emoji',
    id : 'movieToEmoji',
    description : "Converts movie title into emojis",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'Explain Code',
    id : 'explainCode',
    description : "Explain a complicated code in a easy manner",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'Javascript to Python',
    id : 'summary',
    description : "Convert simple js expression to py",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
},
{
    name : 'Create Study Notes',
    id : 'studyNodes',
    description : "Provide a topic and get study notes",
    option : {
        model: "text-davinci-003",
        temperature: 0,
        max_tokens: 100,
        frequency_penalty: 0.0,
        presence_penalty: 0.0,
    },
}]